#pragma once

#include <cstdint>
#include <string>

namespace lt {

// Engine-wide frame type.  All positions and lengths are in sample frames
// at the engine's configured sample rate.
using Frame = int64_t;

// Unique identifiers are plain strings (e.g. UUIDs generated by the Rust
// layer or frontend).  Using std::string keeps the C++ free of extra deps.
using Id = std::string;

// Semitone offset clamped to [-12, +12].
using Semitones = int32_t;

// Gain in linear scale [0.0, ~4.0].  0.0 is silence, 1.0 is unity.
using Gain = float;

} // namespace lt
