/**
 * Wording for the private product dashboard.
 *
 * Lives outside the component so the markup, the client script and the token
 * panel all read the same strings. The component serialises the resolved object
 * into a data attribute; nothing here reaches the client except through that.
 */

export type AnalyticsCopy = Record<string, string>;

const es: AnalyticsCopy = {
  access: "Acceso al panel",
  token: "Token de administracion o de acceso compartido",
  enter: "Abrir metricas",
  exit: "Salir",
  loading: "Calculando metricas...",
  unauthorized: "Token incorrecto, caducado o revocado.",
  notConfigured: "Configura ANALYTICS_ADMIN_TOKEN en Cloudflare Pages.",
  migrationRequired:
    "Falta aplicar la migracion 0007_analytics_access_tokens.sql en la base de datos D1.",
  unavailable: "No se pudieron cargar las metricas.",
  starts: "Inicios",
  devices: "Dispositivos-día activos",
  activation: "Señales de activacion",
  features: "Adopcion de funcionalidades",
  quality: "Fiabilidad de acciones",
  engagement: "Profundidad de sesion",
  maturity: "Madurez de usuarios",
  installationAge: "Antigüedad de instalacion",
  activeDays: "Dias activos acumulados",
  trend: "Actividad diaria",
  adoption: "Adopcion",
  successes: "exitos",
  failures: "fallos",
  updated: "Actualizado",
  overview: "Resumen ejecutivo",
  activationRate: "Tasa de activacion",
  deepSessions: "Sesiones de 30+ min",
  previousPeriod: "frente al periodo anterior",
  previousDay: "frente a ayer a esta hora",
  dailyTrend: "Evolucion diaria",
  utcActivity: "Actividad por hora UTC",
  partialDayNote: "El rango dura menos de un dia: las horas que quedan fuera aparecen a cero.",
  weekly: "Uso por dia de la semana",
  weeklyNote: "Dia local del dispositivo. Un pico en domingo indica uso en directo; una semana plana indica ensayos.",
  sundayShare: "Uso en domingo",
  geography: "Uso por pais",
  geographyNote: "Pais aproximado inferido en el edge; nunca ubicacion precisa.",
  versions: "Versiones instaladas",
  platforms: "Sistemas operativos",
  devicesTitle: "Tipos de dispositivo",
  noData: "Todavia no hay datos para este periodo.",
  sessions: "inicios",
  active: "activos",
  rangeTitle: "Rango de tiempo",
  quickRanges: "Rangos rapidos",
  absoluteRange: "Rango absoluto (UTC)",
  rangeFrom: "Desde",
  rangeTo: "Hasta",
  rangeApply: "Aplicar rango",
  rangeInvalid: "La fecha de inicio debe ser anterior a la de fin.",
  rangeShown: "Rango",
  retentionNote: "Solo se conservan los ultimos 90 dias de telemetria; lo anterior se borra automaticamente.",
  clampedNote: "Rango recortado a los datos disponibles (90 dias de retencion).",
  previousRange: "Desplazar al periodo anterior",
  nextRange: "Desplazar al periodo siguiente",
  refresh: "Recargar",
  range_today: "Hoy",
  range_yesterday: "Ayer",
  range_last6h: "Ultimas 6 horas",
  range_last24h: "Ultimas 24 horas",
  range_last7d: "Ultimos 7 dias",
  range_last14d: "Ultimos 14 dias",
  range_last30d: "Ultimos 30 dias",
  range_last90d: "Ultimos 90 dias",
  range_thisWeek: "Esta semana",
  range_lastWeek: "Semana pasada",
  range_thisMonth: "Este mes",
  range_lastMonth: "Mes pasado",

  filtersTitle: "Filtros activos",
  filtersHint: "Pica en cualquier grafica, pais, version o fila para filtrar el resto del panel.",
  filtersClear: "Quitar todos",
  filterRemove: "Quitar este filtro",
  filterSelfNote: "Esta grafica no se filtra por si misma, para que puedas cambiar de seleccion sin quitar el filtro.",
  dim_country: "Pais",
  dim_version: "Version",
  dim_os: "Sistema",
  dim_device: "Dispositivo",
  dim_hour: "Hora UTC",
  dim_weekday: "Dia",
  dim_installAge: "Antigüedad",
  dim_activeDays: "Dias activos",
  dim_event: "Uso",

  tokensTitle: "Tokens de acceso compartido",
  tokensOpen: "Tokens",
  tokensIntro:
    "Cada token abre este panel en modo solo lectura. No permite crear ni revocar tokens, ni ver nada que no sea este panel.",
  tokensNew: "Crear token",
  tokensLabel: "Para quien es",
  tokensLabelPlaceholder: "Ej. Marcos (disenador)",
  tokensExpiry: "Caducidad",
  tokensCreate: "Generar token",
  tokensGenerating: "Generando...",
  tokensGeneratedTitle: "Token generado",
  tokensGeneratedNote:
    "Copialo ahora: se genera al azar en el servidor y solo se guarda su huella, asi que esta es la unica vez que se muestra. Envialo por un canal privado.",
  tokensCopy: "Copiar token",
  tokensCopied: "Copiado",
  tokensCopyFailed: "No se pudo copiar; selecciona el texto a mano.",
  tokensDone: "Hecho",
  tokensEmpty: "Todavia no hay tokens compartidos.",
  tokensCreated: "Creado",
  tokensExpires: "Caduca",
  tokensNever: "Sin caducidad",
  tokensExpired: "Caducado",
  tokensLastUsed: "Ultimo uso",
  tokensNeverUsed: "Sin usar",
  tokensUses: "usos",
  tokensRevoke: "Revocar",
  tokensRevokeConfirm: "Se revocara el acceso de «{label}» de inmediato. ¿Seguir?",
  tokensInvalidLabel: "Pon una etiqueta para saber de quien es el token.",
  tokensTooMany: "Hay demasiados tokens. Revoca alguno antes de crear otro.",
  tokensFailed: "No se pudo completar la operacion.",
  expiry_24h: "24 horas",
  expiry_7d: "7 dias",
  expiry_30d: "30 dias",
  expiry_90d: "90 dias",
  expiry_365d: "1 año",
  expiry_never: "Sin caducidad",
  guestBadge: "Acceso compartido",
  guestExpires: "Tu acceso caduca el {date}",
  guestNeverExpires: "Tu acceso no caduca",
};

const en: AnalyticsCopy = {
  access: "Dashboard access",
  token: "Administration or shared access token",
  enter: "Open metrics",
  exit: "Sign out",
  loading: "Calculating metrics...",
  unauthorized: "Invalid, expired or revoked token.",
  notConfigured: "Configure ANALYTICS_ADMIN_TOKEN in Cloudflare Pages.",
  migrationRequired:
    "Migration 0007_analytics_access_tokens.sql has not been applied to the D1 database yet.",
  unavailable: "Metrics could not be loaded.",
  starts: "App starts",
  devices: "Active device-days",
  activation: "Activation signals",
  features: "Feature adoption",
  quality: "Action reliability",
  engagement: "Session depth",
  maturity: "User maturity",
  installationAge: "Installation age",
  activeDays: "Cumulative active days",
  trend: "Daily activity",
  adoption: "Adoption",
  successes: "successes",
  failures: "failures",
  updated: "Updated",
  overview: "Executive overview",
  activationRate: "Activation rate",
  deepSessions: "30+ min sessions",
  previousPeriod: "versus previous period",
  previousDay: "versus yesterday at this time",
  dailyTrend: "Daily trend",
  utcActivity: "Activity by UTC hour",
  partialDayNote: "The range is shorter than a day: the hours outside it show as zero.",
  weekly: "Usage by weekday",
  weeklyNote: "Device-local weekday. A Sunday spike means live use; a flat week means rehearsals.",
  sundayShare: "Sunday usage",
  geography: "Usage by country",
  geographyNote: "Approximate country inferred at the edge; never precise location.",
  versions: "Installed versions",
  platforms: "Operating systems",
  devicesTitle: "Device types",
  noData: "No data for this period yet.",
  sessions: "starts",
  active: "active",
  rangeTitle: "Time range",
  quickRanges: "Quick ranges",
  absoluteRange: "Absolute range (UTC)",
  rangeFrom: "From",
  rangeTo: "To",
  rangeApply: "Apply range",
  rangeInvalid: "The start must come before the end.",
  rangeShown: "Range",
  retentionNote: "Only the last 90 days of telemetry are retained; anything older is deleted automatically.",
  clampedNote: "Range trimmed to the available data (90-day retention).",
  previousRange: "Shift to the previous period",
  nextRange: "Shift to the next period",
  refresh: "Reload",
  range_today: "Today",
  range_yesterday: "Yesterday",
  range_last6h: "Last 6 hours",
  range_last24h: "Last 24 hours",
  range_last7d: "Last 7 days",
  range_last14d: "Last 14 days",
  range_last30d: "Last 30 days",
  range_last90d: "Last 90 days",
  range_thisWeek: "This week",
  range_lastWeek: "Last week",
  range_thisMonth: "This month",
  range_lastMonth: "Last month",

  filtersTitle: "Active filters",
  filtersHint: "Click any chart, country, version or row to filter the rest of the dashboard.",
  filtersClear: "Clear all",
  filterRemove: "Remove this filter",
  filterSelfNote: "This chart is not filtered by itself, so you can change the selection without clearing it first.",
  dim_country: "Country",
  dim_version: "Version",
  dim_os: "OS",
  dim_device: "Device",
  dim_hour: "UTC hour",
  dim_weekday: "Weekday",
  dim_installAge: "Install age",
  dim_activeDays: "Active days",
  dim_event: "Usage",

  tokensTitle: "Shared access tokens",
  tokensOpen: "Tokens",
  tokensIntro:
    "Each token opens this dashboard read-only. It cannot create or revoke tokens, and reaches nothing beyond this page.",
  tokensNew: "Create token",
  tokensLabel: "Who it is for",
  tokensLabelPlaceholder: "e.g. Marcos (designer)",
  tokensExpiry: "Expiry",
  tokensCreate: "Generate token",
  tokensGenerating: "Generating...",
  tokensGeneratedTitle: "Token generated",
  tokensGeneratedNote:
    "Copy it now: it is generated at random on the server and only its hash is stored, so this is the only time it is shown. Send it over a private channel.",
  tokensCopy: "Copy token",
  tokensCopied: "Copied",
  tokensCopyFailed: "Could not copy; select the text by hand.",
  tokensDone: "Done",
  tokensEmpty: "No shared tokens yet.",
  tokensCreated: "Created",
  tokensExpires: "Expires",
  tokensNever: "Never expires",
  tokensExpired: "Expired",
  tokensLastUsed: "Last used",
  tokensNeverUsed: "Never used",
  tokensUses: "uses",
  tokensRevoke: "Revoke",
  tokensRevokeConfirm: "This revokes access for “{label}” immediately. Continue?",
  tokensInvalidLabel: "Add a label so you know whose token this is.",
  tokensTooMany: "Too many tokens. Revoke one before creating another.",
  tokensFailed: "The operation could not be completed.",
  expiry_24h: "24 hours",
  expiry_7d: "7 days",
  expiry_30d: "30 days",
  expiry_90d: "90 days",
  expiry_365d: "1 year",
  expiry_never: "Never expires",
  guestBadge: "Shared access",
  guestExpires: "Your access expires on {date}",
  guestNeverExpires: "Your access does not expire",
};

export function analyticsCopy(lang: "en" | "es"): AnalyticsCopy {
  return lang === "en" ? en : es;
}
