#!/usr/bin/env ruby
# frozen_string_literal: true

# Adds the localized InfoPlist.strings (permission texts in English and
# Spanish) to the generated iOS app target.
#
# Info.ios.plist only holds one text per permission. iOS shows the
# translation from <lang>.lproj/InfoPlist.strings inside the app bundle, which
# needs a real localized resource in the Xcode project: a variant group with
# one file per language, plus the languages in the project's knownRegions.
# gen/apple is regenerated by `tauri ios init` on every CI build (it is not in
# git), so this runs after it, like ios-add-privacy-manifest.rb.
#
# Run after `tauri ios init` and before `tauri ios build`. Idempotent.
#
#   ruby scripts/ios-add-localized-strings.rb <App.xcodeproj> <source dir>
#
# <source dir> holds en.lproj/ and es.lproj/; they are copied next to the
# project (SRCROOT) and referenced from there.

require 'fileutils'
require 'xcodeproj'

project_path, source_dir = ARGV

if project_path.nil? || source_dir.nil?
  abort 'usage: ios-add-localized-strings.rb <App.xcodeproj> <dir with *.lproj>'
end

languages = Dir.children(source_dir)
               .select { |name| name.end_with?('.lproj') }
               .map { |name| File.basename(name, '.lproj') }
               .sort
abort "no *.lproj folders in #{source_dir}" if languages.empty?

srcroot = File.dirname(project_path)
languages.each do |language|
  destination = File.join(srcroot, "#{language}.lproj")
  FileUtils.mkdir_p(destination)
  FileUtils.cp(File.join(source_dir, "#{language}.lproj", 'InfoPlist.strings'), destination)
end

project = Xcodeproj::Project.open(project_path)

target = project.targets.find do |candidate|
  candidate.product_type == 'com.apple.product-type.application'
end
abort 'no application target in the generated project' if target.nil?

variant = project.main_group.children.find do |child|
  child.isa == 'PBXVariantGroup' && child.name == 'InfoPlist.strings'
end
variant ||= project.main_group.new_variant_group('InfoPlist.strings')

languages.each do |language|
  path = "#{language}.lproj/InfoPlist.strings"
  next if variant.children.any? { |child| child.path == path }

  reference = variant.new_reference(path)
  reference.name = language
  reference.last_known_file_type = 'text.plist.strings'
end

already_present = target.resources_build_phase.files.any? do |build_file|
  build_file.file_ref == variant
end
target.resources_build_phase.add_file_reference(variant, true) unless already_present

regions = project.root_object.known_regions
(languages + ['Base']).each { |region| regions << region unless regions.include?(region) }

project.save
puts "InfoPlist.strings (#{languages.join(', ')}) is a resource of #{target.name}"
