import type { Config } from "tailwindcss";

const config: Config = {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        "surface-tint": "#3cddc7",
        "surface-bright": "#393939",
        "on-secondary-fixed-variant": "#5c4300",
        "on-tertiary": "#313030",
        "inverse-primary": "#006b5f",
        "primary-container": "#2dd4bf",
        "on-background": "#e5e2e1",
        error: "#ffb4ab",
        "surface-container": "#201f1f",
        "tertiary-container": "#c0bdbd",
        secondary: "#ffe2ab",
        "primary-fixed": "#62fae3",
        tertiary: "#dcd9d8",
        "inverse-surface": "#e5e2e1",
        primary: "#57f1db",
        "on-secondary": "#402d00",
        "on-surface": "#e5e2e1",
        "secondary-fixed": "#ffdfa0",
        "surface-container-highest": "#353534",
        "surface-variant": "#353534",
        outline: "#859490",
        "on-tertiary-fixed": "#1c1b1b",
        "primary-fixed-dim": "#3cddc7",
        "on-primary": "#003731",
        surface: "#131313",
        "surface-dim": "#131313",
        "surface-container-high": "#2a2a2a",
        "on-tertiary-container": "#4d4c4c",
        "on-primary-fixed": "#00201c",
        "on-error-container": "#ffdad6",
        "surface-container-low": "#1c1b1b",
        "on-surface-variant": "#bacac5",
        "on-secondary-fixed": "#261a00",
        "on-secondary-container": "#6d5000",
        "secondary-container": "#ffbf00",
        "surface-container-lowest": "#0e0e0e",
        "error-container": "#93000a",
        "on-tertiary-fixed-variant": "#474746",
        "outline-variant": "#3c4a46",
        "secondary-fixed-dim": "#fbbc00",
        "tertiary-fixed": "#e5e2e1",
        "on-primary-container": "#00574d",
        background: "#131313",
        "on-primary-fixed-variant": "#005047",
        "tertiary-fixed-dim": "#c8c6c5",
        "inverse-on-surface": "#313030",
        "on-error": "#690005",
      },
      fontFamily: {
        headline: ["Inter", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Space Grotesk", "sans-serif"],
        sans: ["Inter", "sans-serif"],
        mono: ["Space Grotesk", "ui-monospace", "SFMono-Regular", "monospace"],
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
    },
  },
  plugins: [],
};

export default config;
