// @generated by scripts/generate-link-proxy.mjs from scripts/link-commands.json.
// Do not edit by hand: change the table and run `npm run gen:link-proxy`.
#![allow(clippy::all, unused_variables)]

use serde_json::Value;
use tauri::{AppHandle, Manager};

use super::proxy::{arg, into_value, into_value_result};

/// The minimum role a proxied command needs on the host. `Custom` ones are
/// handled by hand in `proxy.rs` before `dispatch`.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ProxyAccess {
    View,
    Control,
    Edit,
    Custom,
}

/// None: not a command a guest may run on the host (local to the guest,
/// blocked, or unknown).
pub fn access(command: &str) -> Option<ProxyAccess> {
    match command {
        "get_missing_media"
        | "get_project_load_progress_snapshot"
        | "get_settings"
        | "get_song_view"
        | "get_transport_snapshot"
        | "get_video_thumbnails"
        | "get_waveform_summaries"
        | "get_waveform_window"
        | "is_demo_session"
        | "list_video_assets"
        | "prewarm_timeline_seek"
        | "request_video_thumbnails" => Some(ProxyAccess::View),
        "cancel_marker_jump"
        | "fade_out_and_stop"
        | "pause_transport"
        | "play_transport"
        | "reorder_song_region"
        | "schedule_marker_jump"
        | "schedule_region_jump"
        | "seek_transport"
        | "stop_transport"
        | "toggle_vamp" => Some(ProxyAccess::Control),
        "add_automation_track"
        | "apply_song_arrangement"
        | "assign_section_marker_digit"
        | "capture_song_structure"
        | "commit_track_mix_change"
        | "create_section_marker"
        | "create_song_region"
        | "create_track"
        | "delete_automation_cue"
        | "delete_clip"
        | "delete_clips"
        | "delete_midi_clip"
        | "delete_mix_scene"
        | "delete_section_marker"
        | "delete_song_arrangement"
        | "delete_song_region"
        | "delete_song_tempo_marker"
        | "delete_song_time_signature_marker"
        | "delete_track"
        | "delete_tracks"
        | "delete_video_clips"
        | "discard_song_structure"
        | "duplicate_clip"
        | "duplicate_clips"
        | "duplicate_video_clips"
        | "move_clip"
        | "move_clip_live"
        | "move_clip_to_track"
        | "move_clips_batch"
        | "move_clips_live_batch"
        | "move_midi_clip"
        | "move_song_region"
        | "move_track"
        | "move_video_clip"
        | "redo_action"
        | "remove_automation_track"
        | "save_song_arrangement"
        | "set_automation_track_enabled"
        | "set_automation_track_position"
        | "set_metronome_enabled_realtime"
        | "set_metronome_sound_realtime"
        | "set_metronome_volume_realtime"
        | "set_midi_track_enabled"
        | "set_midi_track_routing"
        | "set_pad_config_realtime"
        | "set_pad_volume_realtime"
        | "set_section_marker_color"
        | "set_section_marker_kind"
        | "set_song_region_chart"
        | "set_song_region_compact_width"
        | "set_voice_guide_config_realtime"
        | "set_voice_guide_volume_realtime"
        | "split_clip"
        | "split_clips"
        | "split_song_region"
        | "split_video_clips"
        | "trim_video_clip"
        | "undo_action"
        | "update_clip_color"
        | "update_clip_window"
        | "update_live_region_master_gain"
        | "update_section_marker"
        | "update_song_region"
        | "update_song_region_fades"
        | "update_song_region_key"
        | "update_song_region_master_gain"
        | "update_song_region_transpose"
        | "update_song_region_warp"
        | "update_song_tempo"
        | "update_song_time_signature"
        | "update_track"
        | "update_track_collapsed"
        | "update_track_color"
        | "update_track_height_offset"
        | "update_track_mix_realtime"
        | "update_track_mono_downmix"
        | "update_track_transpose_enabled"
        | "update_video_clip"
        | "upsert_automation_cue"
        | "upsert_midi_clip"
        | "upsert_mix_scene"
        | "upsert_song_tempo_marker"
        | "upsert_song_time_signature_marker" => Some(ProxyAccess::Edit),
        "save_settings" => Some(ProxyAccess::Custom),
        _ => None,
    }
}

/// Session events the host relays to its guests (mirror mode).
pub const EVENTS_TO_RELAY: &[&str] = &[
    "transport:lifecycle",
    "settings:updated",
    "waveform:ready",
    "waveform:progress",
    "project:load-complete",
    "project:load-progress",
    "audio:meters",
    "audio:region_meters",
    "video:thumbnails-ready",
];

pub const PROXIED_COMMANDS: &[&str] = &[
    "get_missing_media",
    "get_project_load_progress_snapshot",
    "get_settings",
    "get_song_view",
    "get_transport_snapshot",
    "get_video_thumbnails",
    "get_waveform_summaries",
    "get_waveform_window",
    "is_demo_session",
    "list_video_assets",
    "prewarm_timeline_seek",
    "request_video_thumbnails",
    "cancel_marker_jump",
    "fade_out_and_stop",
    "pause_transport",
    "play_transport",
    "reorder_song_region",
    "schedule_marker_jump",
    "schedule_region_jump",
    "seek_transport",
    "stop_transport",
    "toggle_vamp",
    "add_automation_track",
    "apply_song_arrangement",
    "assign_section_marker_digit",
    "capture_song_structure",
    "commit_track_mix_change",
    "create_section_marker",
    "create_song_region",
    "create_track",
    "delete_automation_cue",
    "delete_clip",
    "delete_clips",
    "delete_midi_clip",
    "delete_mix_scene",
    "delete_section_marker",
    "delete_song_arrangement",
    "delete_song_region",
    "delete_song_tempo_marker",
    "delete_song_time_signature_marker",
    "delete_track",
    "delete_tracks",
    "delete_video_clips",
    "discard_song_structure",
    "duplicate_clip",
    "duplicate_clips",
    "duplicate_video_clips",
    "move_clip",
    "move_clip_live",
    "move_clip_to_track",
    "move_clips_batch",
    "move_clips_live_batch",
    "move_midi_clip",
    "move_song_region",
    "move_track",
    "move_video_clip",
    "redo_action",
    "remove_automation_track",
    "save_song_arrangement",
    "set_automation_track_enabled",
    "set_automation_track_position",
    "set_metronome_enabled_realtime",
    "set_metronome_sound_realtime",
    "set_metronome_volume_realtime",
    "set_midi_track_enabled",
    "set_midi_track_routing",
    "set_pad_config_realtime",
    "set_pad_volume_realtime",
    "set_section_marker_color",
    "set_section_marker_kind",
    "set_song_region_chart",
    "set_song_region_compact_width",
    "set_voice_guide_config_realtime",
    "set_voice_guide_volume_realtime",
    "split_clip",
    "split_clips",
    "split_song_region",
    "split_video_clips",
    "trim_video_clip",
    "undo_action",
    "update_clip_color",
    "update_clip_window",
    "update_live_region_master_gain",
    "update_section_marker",
    "update_song_region",
    "update_song_region_fades",
    "update_song_region_key",
    "update_song_region_master_gain",
    "update_song_region_transpose",
    "update_song_region_warp",
    "update_song_tempo",
    "update_song_time_signature",
    "update_track",
    "update_track_collapsed",
    "update_track_color",
    "update_track_height_offset",
    "update_track_mix_realtime",
    "update_track_mono_downmix",
    "update_track_transpose_enabled",
    "update_video_clip",
    "upsert_automation_cue",
    "upsert_midi_clip",
    "upsert_mix_scene",
    "upsert_song_tempo_marker",
    "upsert_song_time_signature_marker",
];

/// Run a proxied command with the guest's arguments, exactly as the host's
/// own UI would through Tauri. The caller has already checked the role.
pub async fn dispatch(app: &AppHandle, command: &str, args: Value) -> Result<Value, String> {
    match command {
        "get_missing_media" => {
            let app = app.clone();
            tauri::async_runtime::spawn_blocking(move || -> Result<Value, String> {
                into_value_result(crate::commands::project::get_missing_media(app.state()))
            })
            .await
            .map_err(|error| error.to_string())?
        }
        "get_project_load_progress_snapshot" => {
            let app = app.clone();
            tauri::async_runtime::spawn_blocking(move || -> Result<Value, String> {
                into_value_result(crate::commands::project::get_project_load_progress_snapshot(app.state()))
            })
            .await
            .map_err(|error| error.to_string())?
        }
        "get_settings" => {
            let app = app.clone();
            tauri::async_runtime::spawn_blocking(move || -> Result<Value, String> {
                into_value_result(crate::commands::settings::get_settings(app.state()))
            })
            .await
            .map_err(|error| error.to_string())?
        }
        "get_song_view" => {
            let app = app.clone();
            tauri::async_runtime::spawn_blocking(move || -> Result<Value, String> {
                into_value_result(crate::commands::project::get_song_view(app.state(), arg(&args, "includeWaveforms")?))
            })
            .await
            .map_err(|error| error.to_string())?
        }
        "get_transport_snapshot" => {
            let app = app.clone();
            tauri::async_runtime::spawn_blocking(move || -> Result<Value, String> {
                into_value_result(crate::commands::transport::get_transport_snapshot(app.state()))
            })
            .await
            .map_err(|error| error.to_string())?
        }
        "get_video_thumbnails" => {
            let app = app.clone();
            tauri::async_runtime::spawn_blocking(move || -> Result<Value, String> {
                into_value(crate::commands::video::get_video_thumbnails(arg(&args, "filePath")?, app.state()))
            })
            .await
            .map_err(|error| error.to_string())?
        }
        "get_waveform_summaries" => {
            let app = app.clone();
            tauri::async_runtime::spawn_blocking(move || -> Result<Value, String> {
                into_value_result(crate::commands::library::get_waveform_summaries(arg(&args, "waveformKeys")?, app.clone(), app.state()))
            })
            .await
            .map_err(|error| error.to_string())?
        }
        "get_waveform_window" => into_value_result(crate::commands::library::get_waveform_window(arg(&args, "waveformKey")?, arg(&args, "startSeconds")?, arg(&args, "endSeconds")?, arg(&args, "bucketCount")?, app.state()).await),
        "is_demo_session" => {
            let app = app.clone();
            tauri::async_runtime::spawn_blocking(move || -> Result<Value, String> {
                into_value(crate::commands::demo::is_demo_session(arg(&args, "sessionFilePath")?))
            })
            .await
            .map_err(|error| error.to_string())?
        }
        "list_video_assets" => {
            let app = app.clone();
            tauri::async_runtime::spawn_blocking(move || -> Result<Value, String> {
                into_value_result(crate::commands::video::list_video_assets(app.state()))
            })
            .await
            .map_err(|error| error.to_string())?
        }
        "prewarm_timeline_seek" => {
            let app = app.clone();
            tauri::async_runtime::spawn_blocking(move || -> Result<Value, String> {
                into_value_result(crate::commands::transport::prewarm_timeline_seek(arg(&args, "positionSeconds")?, app.state()))
            })
            .await
            .map_err(|error| error.to_string())?
        }
        "request_video_thumbnails" => {
            let app = app.clone();
            tauri::async_runtime::spawn_blocking(move || -> Result<Value, String> {
                { crate::commands::video::request_video_thumbnails(arg(&args, "filePaths")?, arg(&args, "urgent")?, app.state()); Ok(Value::Null) }
            })
            .await
            .map_err(|error| error.to_string())?
        }
        "cancel_marker_jump" => {
            let app = app.clone();
            tauri::async_runtime::spawn_blocking(move || -> Result<Value, String> {
                into_value_result(crate::commands::transport::cancel_marker_jump(app.state()))
            })
            .await
            .map_err(|error| error.to_string())?
        }
        "fade_out_and_stop" => {
            let app = app.clone();
            tauri::async_runtime::spawn_blocking(move || -> Result<Value, String> {
                into_value_result(crate::commands::transport::fade_out_and_stop(app.clone(), app.state(), app.state()))
            })
            .await
            .map_err(|error| error.to_string())?
        }
        "pause_transport" => {
            let app = app.clone();
            tauri::async_runtime::spawn_blocking(move || -> Result<Value, String> {
                into_value_result(crate::commands::transport::pause_transport(app.clone(), app.state()))
            })
            .await
            .map_err(|error| error.to_string())?
        }
        "play_transport" => {
            let app = app.clone();
            tauri::async_runtime::spawn_blocking(move || -> Result<Value, String> {
                into_value_result(crate::commands::transport::play_transport(app.clone(), app.state()))
            })
            .await
            .map_err(|error| error.to_string())?
        }
        "reorder_song_region" => {
            let app = app.clone();
            tauri::async_runtime::spawn_blocking(move || -> Result<Value, String> {
                into_value_result(crate::commands::timeline::reorder_song_region(arg(&args, "regionId")?, arg(&args, "targetIndex")?, app.state()))
            })
            .await
            .map_err(|error| error.to_string())?
        }
        "schedule_marker_jump" => {
            let app = app.clone();
            tauri::async_runtime::spawn_blocking(move || -> Result<Value, String> {
                into_value_result(crate::commands::transport::schedule_marker_jump(arg(&args, "targetMarkerId")?, app.state(), app.state()))
            })
            .await
            .map_err(|error| error.to_string())?
        }
        "schedule_region_jump" => {
            let app = app.clone();
            tauri::async_runtime::spawn_blocking(move || -> Result<Value, String> {
                into_value_result(crate::commands::transport::schedule_region_jump(arg(&args, "targetRegionId")?, app.state(), app.state()))
            })
            .await
            .map_err(|error| error.to_string())?
        }
        "seek_transport" => {
            let app = app.clone();
            tauri::async_runtime::spawn_blocking(move || -> Result<Value, String> {
                into_value_result(crate::commands::transport::seek_transport(app.clone(), arg(&args, "positionSeconds")?, app.state()))
            })
            .await
            .map_err(|error| error.to_string())?
        }
        "stop_transport" => {
            let app = app.clone();
            tauri::async_runtime::spawn_blocking(move || -> Result<Value, String> {
                into_value_result(crate::commands::transport::stop_transport(app.clone(), app.state()))
            })
            .await
            .map_err(|error| error.to_string())?
        }
        "toggle_vamp" => {
            let app = app.clone();
            tauri::async_runtime::spawn_blocking(move || -> Result<Value, String> {
                into_value_result(crate::commands::transport::toggle_vamp(arg(&args, "mode")?, arg(&args, "bars")?, app.state()))
            })
            .await
            .map_err(|error| error.to_string())?
        }
        "add_automation_track" => {
            let app = app.clone();
            tauri::async_runtime::spawn_blocking(move || -> Result<Value, String> {
                into_value_result(crate::commands::timeline::add_automation_track(arg(&args, "afterTrackId")?, app.state()))
            })
            .await
            .map_err(|error| error.to_string())?
        }
        "apply_song_arrangement" => {
            let app = app.clone();
            tauri::async_runtime::spawn_blocking(move || -> Result<Value, String> {
                into_value_result(crate::commands::timeline::apply_song_arrangement(arg(&args, "regionId")?, arg(&args, "arrangementId")?, app.state()))
            })
            .await
            .map_err(|error| error.to_string())?
        }
        "assign_section_marker_digit" => {
            let app = app.clone();
            tauri::async_runtime::spawn_blocking(move || -> Result<Value, String> {
                into_value_result(crate::commands::timeline::assign_section_marker_digit(arg(&args, "sectionId")?, arg(&args, "digit")?, app.state()))
            })
            .await
            .map_err(|error| error.to_string())?
        }
        "capture_song_structure" => {
            let app = app.clone();
            tauri::async_runtime::spawn_blocking(move || -> Result<Value, String> {
                into_value_result(crate::commands::timeline::capture_song_structure(arg(&args, "regionId")?, app.state()))
            })
            .await
            .map_err(|error| error.to_string())?
        }
        "commit_track_mix_change" => {
            let app = app.clone();
            tauri::async_runtime::spawn_blocking(move || -> Result<Value, String> {
                into_value_result(crate::commands::timeline::commit_track_mix_change(arg(&args, "trackId")?, arg(&args, "volume")?, arg(&args, "pan")?, arg(&args, "muted")?, arg(&args, "solo")?, arg(&args, "audioTo")?, app.state()))
            })
            .await
            .map_err(|error| error.to_string())?
        }
        "create_section_marker" => {
            let app = app.clone();
            tauri::async_runtime::spawn_blocking(move || -> Result<Value, String> {
                into_value_result(crate::commands::timeline::create_section_marker(arg(&args, "startSeconds")?, arg(&args, "kind")?, arg(&args, "variant")?, arg(&args, "name")?, app.state()))
            })
            .await
            .map_err(|error| error.to_string())?
        }
        "create_song_region" => {
            let app = app.clone();
            tauri::async_runtime::spawn_blocking(move || -> Result<Value, String> {
                into_value_result(crate::commands::timeline::create_song_region(arg(&args, "startSeconds")?, arg(&args, "endSeconds")?, app.state()))
            })
            .await
            .map_err(|error| error.to_string())?
        }
        "create_track" => {
            let app = app.clone();
            tauri::async_runtime::spawn_blocking(move || -> Result<Value, String> {
                into_value_result(crate::commands::timeline::create_track(arg(&args, "name")?, arg(&args, "kind")?, arg(&args, "insertAfterTrackId")?, arg(&args, "parentTrackId")?, app.state()))
            })
            .await
            .map_err(|error| error.to_string())?
        }
        "delete_automation_cue" => {
            let app = app.clone();
            tauri::async_runtime::spawn_blocking(move || -> Result<Value, String> {
                into_value_result(crate::commands::timeline::delete_automation_cue(arg(&args, "cueId")?, app.state()))
            })
            .await
            .map_err(|error| error.to_string())?
        }
        "delete_clip" => {
            let app = app.clone();
            tauri::async_runtime::spawn_blocking(move || -> Result<Value, String> {
                into_value_result(crate::commands::timeline::delete_clip(arg(&args, "clipId")?, app.state()))
            })
            .await
            .map_err(|error| error.to_string())?
        }
        "delete_clips" => {
            let app = app.clone();
            tauri::async_runtime::spawn_blocking(move || -> Result<Value, String> {
                into_value_result(crate::commands::timeline::delete_clips(arg(&args, "clipIds")?, app.state()))
            })
            .await
            .map_err(|error| error.to_string())?
        }
        "delete_midi_clip" => {
            let app = app.clone();
            tauri::async_runtime::spawn_blocking(move || -> Result<Value, String> {
                into_value_result(crate::commands::timeline::delete_midi_clip(arg(&args, "clipId")?, app.state()))
            })
            .await
            .map_err(|error| error.to_string())?
        }
        "delete_mix_scene" => {
            let app = app.clone();
            tauri::async_runtime::spawn_blocking(move || -> Result<Value, String> {
                into_value_result(crate::commands::timeline::delete_mix_scene(arg(&args, "sceneId")?, app.state()))
            })
            .await
            .map_err(|error| error.to_string())?
        }
        "delete_section_marker" => {
            let app = app.clone();
            tauri::async_runtime::spawn_blocking(move || -> Result<Value, String> {
                into_value_result(crate::commands::timeline::delete_section_marker(arg(&args, "sectionId")?, app.state()))
            })
            .await
            .map_err(|error| error.to_string())?
        }
        "delete_song_arrangement" => {
            let app = app.clone();
            tauri::async_runtime::spawn_blocking(move || -> Result<Value, String> {
                into_value_result(crate::commands::timeline::delete_song_arrangement(arg(&args, "regionId")?, arg(&args, "arrangementId")?, app.state()))
            })
            .await
            .map_err(|error| error.to_string())?
        }
        "delete_song_region" => {
            let app = app.clone();
            tauri::async_runtime::spawn_blocking(move || -> Result<Value, String> {
                into_value_result(crate::commands::timeline::delete_song_region(arg(&args, "regionId")?, app.state()))
            })
            .await
            .map_err(|error| error.to_string())?
        }
        "delete_song_tempo_marker" => {
            let app = app.clone();
            tauri::async_runtime::spawn_blocking(move || -> Result<Value, String> {
                into_value_result(crate::commands::timeline::delete_song_tempo_marker(arg(&args, "markerId")?, app.state()))
            })
            .await
            .map_err(|error| error.to_string())?
        }
        "delete_song_time_signature_marker" => {
            let app = app.clone();
            tauri::async_runtime::spawn_blocking(move || -> Result<Value, String> {
                into_value_result(crate::commands::timeline::delete_song_time_signature_marker(arg(&args, "markerId")?, app.state()))
            })
            .await
            .map_err(|error| error.to_string())?
        }
        "delete_track" => {
            let app = app.clone();
            tauri::async_runtime::spawn_blocking(move || -> Result<Value, String> {
                into_value_result(crate::commands::timeline::delete_track(arg(&args, "trackId")?, app.state()))
            })
            .await
            .map_err(|error| error.to_string())?
        }
        "delete_tracks" => {
            let app = app.clone();
            tauri::async_runtime::spawn_blocking(move || -> Result<Value, String> {
                into_value_result(crate::commands::timeline::delete_tracks(arg(&args, "trackIds")?, app.state()))
            })
            .await
            .map_err(|error| error.to_string())?
        }
        "delete_video_clips" => {
            let app = app.clone();
            tauri::async_runtime::spawn_blocking(move || -> Result<Value, String> {
                into_value_result(crate::commands::video::delete_video_clips(arg(&args, "clipIds")?, app.state()))
            })
            .await
            .map_err(|error| error.to_string())?
        }
        "discard_song_structure" => {
            let app = app.clone();
            tauri::async_runtime::spawn_blocking(move || -> Result<Value, String> {
                into_value_result(crate::commands::timeline::discard_song_structure(arg(&args, "regionId")?, app.state()))
            })
            .await
            .map_err(|error| error.to_string())?
        }
        "duplicate_clip" => {
            let app = app.clone();
            tauri::async_runtime::spawn_blocking(move || -> Result<Value, String> {
                into_value_result(crate::commands::timeline::duplicate_clip(arg(&args, "clipId")?, arg(&args, "timelineStartSeconds")?, app.state()))
            })
            .await
            .map_err(|error| error.to_string())?
        }
        "duplicate_clips" => {
            let app = app.clone();
            tauri::async_runtime::spawn_blocking(move || -> Result<Value, String> {
                into_value_result(crate::commands::timeline::duplicate_clips(arg(&args, "placements")?, app.state()))
            })
            .await
            .map_err(|error| error.to_string())?
        }
        "duplicate_video_clips" => {
            let app = app.clone();
            tauri::async_runtime::spawn_blocking(move || -> Result<Value, String> {
                into_value_result(crate::commands::video::duplicate_video_clips(arg(&args, "clipIds")?, app.state()))
            })
            .await
            .map_err(|error| error.to_string())?
        }
        "move_clip" => {
            let app = app.clone();
            tauri::async_runtime::spawn_blocking(move || -> Result<Value, String> {
                into_value_result(crate::commands::timeline::move_clip(arg(&args, "clipId")?, arg(&args, "timelineStartSeconds")?, app.state()))
            })
            .await
            .map_err(|error| error.to_string())?
        }
        "move_clip_live" => {
            let app = app.clone();
            tauri::async_runtime::spawn_blocking(move || -> Result<Value, String> {
                into_value_result(crate::commands::timeline::move_clip_live(arg(&args, "clipId")?, arg(&args, "timelineStartSeconds")?, app.state()))
            })
            .await
            .map_err(|error| error.to_string())?
        }
        "move_clip_to_track" => {
            let app = app.clone();
            tauri::async_runtime::spawn_blocking(move || -> Result<Value, String> {
                into_value_result(crate::commands::timeline::move_clip_to_track(arg(&args, "clipId")?, arg(&args, "targetTrackId")?, app.state()))
            })
            .await
            .map_err(|error| error.to_string())?
        }
        "move_clips_batch" => {
            let app = app.clone();
            tauri::async_runtime::spawn_blocking(move || -> Result<Value, String> {
                into_value_result(crate::commands::timeline::move_clips_batch(arg(&args, "moves")?, app.state()))
            })
            .await
            .map_err(|error| error.to_string())?
        }
        "move_clips_live_batch" => {
            let app = app.clone();
            tauri::async_runtime::spawn_blocking(move || -> Result<Value, String> {
                into_value_result(crate::commands::timeline::move_clips_live_batch(arg(&args, "moves")?, app.state()))
            })
            .await
            .map_err(|error| error.to_string())?
        }
        "move_midi_clip" => {
            let app = app.clone();
            tauri::async_runtime::spawn_blocking(move || -> Result<Value, String> {
                into_value_result(crate::commands::timeline::move_midi_clip(arg(&args, "clipId")?, arg(&args, "timelineStartSeconds")?, arg(&args, "targetTrackId")?, app.state()))
            })
            .await
            .map_err(|error| error.to_string())?
        }
        "move_song_region" => {
            let app = app.clone();
            tauri::async_runtime::spawn_blocking(move || -> Result<Value, String> {
                into_value_result(crate::commands::timeline::move_song_region(arg(&args, "regionId")?, arg(&args, "deltaSeconds")?, app.state()))
            })
            .await
            .map_err(|error| error.to_string())?
        }
        "move_track" => {
            let app = app.clone();
            tauri::async_runtime::spawn_blocking(move || -> Result<Value, String> {
                into_value_result(crate::commands::timeline::move_track(arg(&args, "trackId")?, arg(&args, "insertAfterTrackId")?, arg(&args, "insertBeforeTrackId")?, arg(&args, "parentTrackId")?, app.state()))
            })
            .await
            .map_err(|error| error.to_string())?
        }
        "move_video_clip" => {
            let app = app.clone();
            tauri::async_runtime::spawn_blocking(move || -> Result<Value, String> {
                into_value_result(crate::commands::video::move_video_clip(arg(&args, "clipId")?, arg(&args, "timelineStartSeconds")?, arg(&args, "targetTrackId")?, app.state()))
            })
            .await
            .map_err(|error| error.to_string())?
        }
        "redo_action" => {
            let app = app.clone();
            tauri::async_runtime::spawn_blocking(move || -> Result<Value, String> {
                into_value_result(crate::commands::timeline::redo_action(app.state()))
            })
            .await
            .map_err(|error| error.to_string())?
        }
        "remove_automation_track" => {
            let app = app.clone();
            tauri::async_runtime::spawn_blocking(move || -> Result<Value, String> {
                into_value_result(crate::commands::timeline::remove_automation_track(app.state()))
            })
            .await
            .map_err(|error| error.to_string())?
        }
        "save_song_arrangement" => {
            let app = app.clone();
            tauri::async_runtime::spawn_blocking(move || -> Result<Value, String> {
                into_value_result(crate::commands::timeline::save_song_arrangement(arg(&args, "regionId")?, arg(&args, "arrangement")?, arg(&args, "apply")?, app.state()))
            })
            .await
            .map_err(|error| error.to_string())?
        }
        "set_automation_track_enabled" => {
            let app = app.clone();
            tauri::async_runtime::spawn_blocking(move || -> Result<Value, String> {
                into_value_result(crate::commands::timeline::set_automation_track_enabled(arg(&args, "enabled")?, app.state()))
            })
            .await
            .map_err(|error| error.to_string())?
        }
        "set_automation_track_position" => {
            let app = app.clone();
            tauri::async_runtime::spawn_blocking(move || -> Result<Value, String> {
                into_value_result(crate::commands::timeline::set_automation_track_position(arg(&args, "afterTrackId")?, app.state()))
            })
            .await
            .map_err(|error| error.to_string())?
        }
        "set_metronome_enabled_realtime" => {
            let app = app.clone();
            tauri::async_runtime::spawn_blocking(move || -> Result<Value, String> {
                into_value_result(crate::commands::settings::set_metronome_enabled_realtime(arg(&args, "enabled")?, app.state()))
            })
            .await
            .map_err(|error| error.to_string())?
        }
        "set_metronome_sound_realtime" => {
            let app = app.clone();
            tauri::async_runtime::spawn_blocking(move || -> Result<Value, String> {
                into_value_result(crate::commands::settings::set_metronome_sound_realtime(app.clone(), arg(&args, "settings")?, app.state(), app.state()))
            })
            .await
            .map_err(|error| error.to_string())?
        }
        "set_metronome_volume_realtime" => {
            let app = app.clone();
            tauri::async_runtime::spawn_blocking(move || -> Result<Value, String> {
                into_value_result(crate::commands::settings::set_metronome_volume_realtime(arg(&args, "volume")?, app.state()))
            })
            .await
            .map_err(|error| error.to_string())?
        }
        "set_midi_track_enabled" => {
            let app = app.clone();
            tauri::async_runtime::spawn_blocking(move || -> Result<Value, String> {
                into_value_result(crate::commands::timeline::set_midi_track_enabled(arg(&args, "trackId")?, arg(&args, "enabled")?, app.state()))
            })
            .await
            .map_err(|error| error.to_string())?
        }
        "set_midi_track_routing" => {
            let app = app.clone();
            tauri::async_runtime::spawn_blocking(move || -> Result<Value, String> {
                into_value_result(crate::commands::timeline::set_midi_track_routing(arg(&args, "trackId")?, arg(&args, "port")?, arg(&args, "channel")?, app.state()))
            })
            .await
            .map_err(|error| error.to_string())?
        }
        "set_pad_config_realtime" => {
            let app = app.clone();
            tauri::async_runtime::spawn_blocking(move || -> Result<Value, String> {
                into_value_result(crate::commands::pads::set_pad_config_realtime(app.clone(), arg(&args, "settings")?, app.state(), app.state()))
            })
            .await
            .map_err(|error| error.to_string())?
        }
        "set_pad_volume_realtime" => {
            let app = app.clone();
            tauri::async_runtime::spawn_blocking(move || -> Result<Value, String> {
                into_value_result(crate::commands::pads::set_pad_volume_realtime(arg(&args, "volume")?, app.state()))
            })
            .await
            .map_err(|error| error.to_string())?
        }
        "set_section_marker_color" => {
            let app = app.clone();
            tauri::async_runtime::spawn_blocking(move || -> Result<Value, String> {
                into_value_result(crate::commands::timeline::set_section_marker_color(arg(&args, "sectionId")?, arg(&args, "color")?, app.state()))
            })
            .await
            .map_err(|error| error.to_string())?
        }
        "set_section_marker_kind" => {
            let app = app.clone();
            tauri::async_runtime::spawn_blocking(move || -> Result<Value, String> {
                into_value_result(crate::commands::timeline::set_section_marker_kind(arg(&args, "sectionId")?, arg(&args, "kind")?, arg(&args, "variant")?, app.state()))
            })
            .await
            .map_err(|error| error.to_string())?
        }
        "set_song_region_chart" => {
            let app = app.clone();
            tauri::async_runtime::spawn_blocking(move || -> Result<Value, String> {
                into_value_result(crate::commands::charts::set_song_region_chart(arg(&args, "regionId")?, arg(&args, "chart")?, app.state()))
            })
            .await
            .map_err(|error| error.to_string())?
        }
        "set_song_region_compact_width" => {
            let app = app.clone();
            tauri::async_runtime::spawn_blocking(move || -> Result<Value, String> {
                into_value_result(crate::commands::timeline::set_song_region_compact_width(arg(&args, "regionId")?, arg(&args, "widthRem")?, app.state()))
            })
            .await
            .map_err(|error| error.to_string())?
        }
        "set_voice_guide_config_realtime" => {
            let app = app.clone();
            tauri::async_runtime::spawn_blocking(move || -> Result<Value, String> {
                into_value_result(crate::commands::settings::set_voice_guide_config_realtime(app.clone(), arg(&args, "settings")?, app.state(), app.state()))
            })
            .await
            .map_err(|error| error.to_string())?
        }
        "set_voice_guide_volume_realtime" => {
            let app = app.clone();
            tauri::async_runtime::spawn_blocking(move || -> Result<Value, String> {
                into_value_result(crate::commands::settings::set_voice_guide_volume_realtime(arg(&args, "volume")?, app.state()))
            })
            .await
            .map_err(|error| error.to_string())?
        }
        "split_clip" => {
            let app = app.clone();
            tauri::async_runtime::spawn_blocking(move || -> Result<Value, String> {
                into_value_result(crate::commands::timeline::split_clip(arg(&args, "clipId")?, arg(&args, "splitSeconds")?, app.state()))
            })
            .await
            .map_err(|error| error.to_string())?
        }
        "split_clips" => {
            let app = app.clone();
            tauri::async_runtime::spawn_blocking(move || -> Result<Value, String> {
                into_value_result(crate::commands::timeline::split_clips(arg(&args, "clipIds")?, arg(&args, "splitSeconds")?, app.state()))
            })
            .await
            .map_err(|error| error.to_string())?
        }
        "split_song_region" => {
            let app = app.clone();
            tauri::async_runtime::spawn_blocking(move || -> Result<Value, String> {
                into_value_result(crate::commands::timeline::split_song_region(arg(&args, "regionId")?, arg(&args, "splitSeconds")?, app.state()))
            })
            .await
            .map_err(|error| error.to_string())?
        }
        "split_video_clips" => {
            let app = app.clone();
            tauri::async_runtime::spawn_blocking(move || -> Result<Value, String> {
                into_value_result(crate::commands::video::split_video_clips(arg(&args, "clipIds")?, arg(&args, "splitSeconds")?, app.state()))
            })
            .await
            .map_err(|error| error.to_string())?
        }
        "trim_video_clip" => {
            let app = app.clone();
            tauri::async_runtime::spawn_blocking(move || -> Result<Value, String> {
                into_value_result(crate::commands::video::trim_video_clip(arg(&args, "clipId")?, arg(&args, "startSeconds")?, arg(&args, "endSeconds")?, app.state()))
            })
            .await
            .map_err(|error| error.to_string())?
        }
        "undo_action" => {
            let app = app.clone();
            tauri::async_runtime::spawn_blocking(move || -> Result<Value, String> {
                into_value_result(crate::commands::timeline::undo_action(app.state()))
            })
            .await
            .map_err(|error| error.to_string())?
        }
        "update_clip_color" => {
            let app = app.clone();
            tauri::async_runtime::spawn_blocking(move || -> Result<Value, String> {
                into_value_result(crate::commands::timeline::update_clip_color(arg(&args, "clipId")?, arg(&args, "color")?, app.state()))
            })
            .await
            .map_err(|error| error.to_string())?
        }
        "update_clip_window" => {
            let app = app.clone();
            tauri::async_runtime::spawn_blocking(move || -> Result<Value, String> {
                into_value_result(crate::commands::timeline::update_clip_window(arg(&args, "clipId")?, arg(&args, "timelineStartSeconds")?, arg(&args, "sourceStartSeconds")?, arg(&args, "durationSeconds")?, app.state()))
            })
            .await
            .map_err(|error| error.to_string())?
        }
        "update_live_region_master_gain" => {
            let app = app.clone();
            tauri::async_runtime::spawn_blocking(move || -> Result<Value, String> {
                into_value_result(crate::commands::timeline::update_live_region_master_gain(arg(&args, "regionId")?, arg(&args, "masterGain")?, app.state()))
            })
            .await
            .map_err(|error| error.to_string())?
        }
        "update_section_marker" => {
            let app = app.clone();
            tauri::async_runtime::spawn_blocking(move || -> Result<Value, String> {
                into_value_result(crate::commands::timeline::update_section_marker(arg(&args, "sectionId")?, arg(&args, "name")?, arg(&args, "startSeconds")?, arg(&args, "// Set only when the drag crossed into the other ruler lane; `None` leaves
    // the marker's existing category untouched.
    categoryOverride")?, app.state()))
            })
            .await
            .map_err(|error| error.to_string())?
        }
        "update_song_region" => {
            let app = app.clone();
            tauri::async_runtime::spawn_blocking(move || -> Result<Value, String> {
                into_value_result(crate::commands::timeline::update_song_region(arg(&args, "regionId")?, arg(&args, "name")?, arg(&args, "startSeconds")?, arg(&args, "endSeconds")?, app.state()))
            })
            .await
            .map_err(|error| error.to_string())?
        }
        "update_song_region_fades" => {
            let app = app.clone();
            tauri::async_runtime::spawn_blocking(move || -> Result<Value, String> {
                into_value_result(crate::commands::timeline::update_song_region_fades(arg(&args, "regionId")?, arg(&args, "fadeInSeconds")?, arg(&args, "fadeOutSeconds")?, app.state()))
            })
            .await
            .map_err(|error| error.to_string())?
        }
        "update_song_region_key" => {
            let app = app.clone();
            tauri::async_runtime::spawn_blocking(move || -> Result<Value, String> {
                into_value_result(crate::commands::timeline::update_song_region_key(arg(&args, "regionId")?, arg(&args, "key")?, app.state()))
            })
            .await
            .map_err(|error| error.to_string())?
        }
        "update_song_region_master_gain" => {
            let app = app.clone();
            tauri::async_runtime::spawn_blocking(move || -> Result<Value, String> {
                into_value_result(crate::commands::timeline::update_song_region_master_gain(arg(&args, "regionId")?, arg(&args, "masterGain")?, app.state()))
            })
            .await
            .map_err(|error| error.to_string())?
        }
        "update_song_region_transpose" => {
            let app = app.clone();
            tauri::async_runtime::spawn_blocking(move || -> Result<Value, String> {
                into_value_result(crate::commands::timeline::update_song_region_transpose(arg(&args, "regionId")?, arg(&args, "transposeSemitones")?, app.state()))
            })
            .await
            .map_err(|error| error.to_string())?
        }
        "update_song_region_warp" => {
            let app = app.clone();
            tauri::async_runtime::spawn_blocking(move || -> Result<Value, String> {
                into_value_result(crate::commands::timeline::update_song_region_warp(arg(&args, "regionId")?, arg(&args, "warpEnabled")?, arg(&args, "warpSourceBpm")?, app.state()))
            })
            .await
            .map_err(|error| error.to_string())?
        }
        "update_song_tempo" => {
            let app = app.clone();
            tauri::async_runtime::spawn_blocking(move || -> Result<Value, String> {
                into_value_result(crate::commands::timeline::update_song_tempo(arg(&args, "bpm")?, app.state()))
            })
            .await
            .map_err(|error| error.to_string())?
        }
        "update_song_time_signature" => {
            let app = app.clone();
            tauri::async_runtime::spawn_blocking(move || -> Result<Value, String> {
                into_value_result(crate::commands::timeline::update_song_time_signature(arg(&args, "signature")?, app.state()))
            })
            .await
            .map_err(|error| error.to_string())?
        }
        "update_track" => {
            let app = app.clone();
            tauri::async_runtime::spawn_blocking(move || -> Result<Value, String> {
                into_value_result(crate::commands::timeline::update_track(arg(&args, "trackId")?, arg(&args, "name")?, app.state()))
            })
            .await
            .map_err(|error| error.to_string())?
        }
        "update_track_collapsed" => {
            let app = app.clone();
            tauri::async_runtime::spawn_blocking(move || -> Result<Value, String> {
                into_value_result(crate::commands::timeline::update_track_collapsed(arg(&args, "trackId")?, arg(&args, "collapsed")?, app.state()))
            })
            .await
            .map_err(|error| error.to_string())?
        }
        "update_track_color" => {
            let app = app.clone();
            tauri::async_runtime::spawn_blocking(move || -> Result<Value, String> {
                into_value_result(crate::commands::timeline::update_track_color(arg(&args, "trackId")?, arg(&args, "color")?, app.state()))
            })
            .await
            .map_err(|error| error.to_string())?
        }
        "update_track_height_offset" => {
            let app = app.clone();
            tauri::async_runtime::spawn_blocking(move || -> Result<Value, String> {
                into_value_result(crate::commands::timeline::update_track_height_offset(arg(&args, "trackId")?, arg(&args, "heightOffset")?, app.state()))
            })
            .await
            .map_err(|error| error.to_string())?
        }
        "update_track_mix_realtime" => {
            let app = app.clone();
            tauri::async_runtime::spawn_blocking(move || -> Result<Value, String> {
                into_value_result(crate::commands::timeline::update_track_mix_realtime(arg(&args, "trackId")?, arg(&args, "volume")?, arg(&args, "pan")?, arg(&args, "muted")?, arg(&args, "solo")?, app.state()))
            })
            .await
            .map_err(|error| error.to_string())?
        }
        "update_track_mono_downmix" => {
            let app = app.clone();
            tauri::async_runtime::spawn_blocking(move || -> Result<Value, String> {
                into_value_result(crate::commands::timeline::update_track_mono_downmix(arg(&args, "trackId")?, arg(&args, "monoDownmix")?, app.state()))
            })
            .await
            .map_err(|error| error.to_string())?
        }
        "update_track_transpose_enabled" => {
            let app = app.clone();
            tauri::async_runtime::spawn_blocking(move || -> Result<Value, String> {
                into_value_result(crate::commands::timeline::update_track_transpose_enabled(arg(&args, "trackId")?, arg(&args, "transposeEnabled")?, app.state()))
            })
            .await
            .map_err(|error| error.to_string())?
        }
        "update_video_clip" => {
            let app = app.clone();
            tauri::async_runtime::spawn_blocking(move || -> Result<Value, String> {
                into_value_result(crate::commands::video::update_video_clip(arg(&args, "clipId")?, arg(&args, "props")?, app.state()))
            })
            .await
            .map_err(|error| error.to_string())?
        }
        "upsert_automation_cue" => {
            let app = app.clone();
            tauri::async_runtime::spawn_blocking(move || -> Result<Value, String> {
                into_value_result(crate::commands::timeline::upsert_automation_cue(arg(&args, "cue")?, app.state()))
            })
            .await
            .map_err(|error| error.to_string())?
        }
        "upsert_midi_clip" => {
            let app = app.clone();
            tauri::async_runtime::spawn_blocking(move || -> Result<Value, String> {
                into_value_result(crate::commands::timeline::upsert_midi_clip(arg(&args, "clip")?, app.state()))
            })
            .await
            .map_err(|error| error.to_string())?
        }
        "upsert_mix_scene" => {
            let app = app.clone();
            tauri::async_runtime::spawn_blocking(move || -> Result<Value, String> {
                into_value_result(crate::commands::timeline::upsert_mix_scene(arg(&args, "scene")?, app.state()))
            })
            .await
            .map_err(|error| error.to_string())?
        }
        "upsert_song_tempo_marker" => {
            let app = app.clone();
            tauri::async_runtime::spawn_blocking(move || -> Result<Value, String> {
                into_value_result(crate::commands::timeline::upsert_song_tempo_marker(arg(&args, "startSeconds")?, arg(&args, "bpm")?, app.state()))
            })
            .await
            .map_err(|error| error.to_string())?
        }
        "upsert_song_time_signature_marker" => {
            let app = app.clone();
            tauri::async_runtime::spawn_blocking(move || -> Result<Value, String> {
                into_value_result(crate::commands::timeline::upsert_song_time_signature_marker(arg(&args, "startSeconds")?, arg(&args, "signature")?, app.state()))
            })
            .await
            .map_err(|error| error.to_string())?
        }
        _ => Err(format!("notProxied:{command}")),
    }
}
